danceapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    
    # Account management
    path("register", views.register_student, name="register_student"),
    path("register_teacher", views.register_teacher, name="register_teacher"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("change_password", views.change_password, name="change_password"),

    # Teacher only
    path("new_video", views.new_video, name="new_video"),

    # Student only
    path("saved_videos", views.saved_videos, name="saved_videos"),

    # Notifications
    path("notifications", views.notifications, name="notifications"),

    # Video page
    path("video/<int:video_id>", views.video, name="video"),
    path("add_comment/<int:video_id>", views.add_comment, name="add_comment"),

    # API Routes (returning JSON responses)
    path("videos/<str:mode>", views.videos, name ="videos"),
    path("add_step", views.add_step, name="add_step"),
    path("update_favourites/<int:video_id>", views.update_favourites, name="update_favourites"),
    path("delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
    path("read_notification/<int:notification_id>", views.read_notification, name="read_notification"),
    path("read_all_notifications", views.read_all_notifications, name="read_all_notifications"),
    path("reset_notifications_counter", views.reset_notifications_counter, name="reset_notifications_counter")
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("danceapp.urls")),
]

danceapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass
    # Flag that determines whether the user is a student or teacher
    is_student = models.BooleanField('student status', default=False)
    is_teacher = models.BooleanField('teacher status', default=False)
    profile_picture = models.URLField(max_length=700, blank=True)
    unread_notifications = models.IntegerField(default=0)

    def __str__(self):
        if (self.is_student):
            return f"{self.first_name} {self.last_name} (Student)"
        elif (self.is_teacher):
            return f"{self.first_name} (Teacher)"
        else:
            return f"{self.username} (Other)"

    class Meta: 
        # Orders users by first name
        ordering = ['first_name']

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
    class Meta: 
        # Orders students by first name
        ordering = ['user']
    

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        if (self.user.first_name):
            return self.user.first_name
        else:
            return self.user.username

    class Meta: 
        # Orders teachers by first name
        ordering = ['user']

class Style(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    class Meta: 
        # Orders styles by name
        ordering = ['name']

class CalenaStep(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name
    
    class Meta: 
        # Orders styles by name
        ordering = ['name']

class Video(models.Model):
    LEVELS = [('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')]
    
    title = models.CharField(max_length=59)
    youtube_id = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    thumbnail_url = models.URLField(max_length=600)
    style = models.ForeignKey(Style, on_delete=models.CASCADE)
    level = models.CharField(max_length=10, choices=LEVELS)
    teacher = models.ManyToManyField(Teacher, related_name="videos")
    student_access = models.ManyToManyField(Student, blank=True, related_name="videos")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    class_date = models.DateField()
    saved_by = models.ManyToManyField(Student, related_name="favourites", blank=True)
    # Field is only populated for salsa calena videos
    calena_steps = models.ManyToManyField(CalenaStep, related_name="videos", blank=True)

    def __str__(self):
        return f"{self.title} uploaded by {self.author.first_name}"

    def serialize(self):
        return {
            "id": self.id,
            "title": self.title,
            "youtube_id": self.youtube_id, 
            "thumbnail_url": self.thumbnail_url,
            "style": self.style.pk,
            "level": self.level,
            "teacher": [{"name": teacher.user.first_name, "value": teacher.pk} for teacher in self.teacher.all()],
            "class_date": self.class_date.strftime("%d/%m/%Y"),
            "calena_steps": [step.pk for step in self.calena_steps.all()],
        }
    
    class Meta:
        # Orders videos in reverse chronological order
        ordering = ['-class_date']

class Comment(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    comment = models.CharField(max_length=5000)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.comment)

    class Meta: 
        # Orders comment by most recent first, by default
        ordering = ['-time']

class Notification(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name="notifications")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notifications")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="updates")
    message = models.CharField(max_length=5000)
    time = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"Notification for {self.user.first_name} : {self.message}"
    
    class Meta:
        # Orders notifications by most recent first by default
        ordering = ['-time']

danceapp/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.db import IntegrityError
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from .models import User, Student, Video, Teacher, Style, Notification, CalenaStep, Comment
from .forms import NewVideoForm, CommentForm, PasswordChangeForm
from . import util

@login_required(login_url='/login')
def index(request):

    # Needed for filter dropdowns
    teachers = Teacher.objects.all()
    styles = Style.objects.all()

    return render(request, "danceapp/index.html", {
        "teachers": teachers,
        "styles": styles,
        "levels": Video.LEVELS,
        "steps": CalenaStep.objects.all()
    })

# API route
@login_required(login_url='/login')
def videos(request, mode):
    
    try:
        user = User.objects.get(pk=request.user.pk)
    except User.DoesNotExist:
        return JsonResponse({"error": "User does not exist."}, status=400)

    # Used by index page
    if mode == "all":
        videos = util.get_user_videos(request)
    
    # Used by saved video page
    elif mode == "saved":
        if user.is_student == True:
            user = user.student
            videos = user.favourites.all()
        else:
            return JsonResponse({"error": "Only student profiles can make this request."}, status=400)
    else:
        return JsonResponse({"error": "You must set mode to \"saved\" or \"all\"."}, status=400)
            
    return JsonResponse([video.serialize() for video in videos], safe=False)

@login_required(login_url='/login')
@csrf_exempt
def add_step(request):
    
    if request.method != 'POST':
        return JsonResponse({"error": "POST request required."}, status=400)

    current_steps = CalenaStep.objects.values_list('name', flat=True).order_by('name')

    # Gets data from POST request and pulls out step name
    data = json.loads(request.body)
    step_name = data.get("step_name")
    # We convert the provided step name to lower and then capitalize it to allow consistency
    step_name = step_name.lower()
    step_name = step_name.capitalize()

    # Cannot add a blank step name to the database
    if len(step_name) == 0:
        error_for_page_html = "You cannot submit a step with no name. Please try again."
        return JsonResponse({"error": error_for_page_html}, status=400)
    
    if step_name in current_steps:
        error_for_page_html = "This step is already saved in the database, please add a different step."
        return JsonResponse({"error": error_for_page_html}, status=400)

    try: 
        new_step = CalenaStep(name=step_name)
        new_step.save()
    except:
        return JsonResponse({"error": "An error has occurred when attempting to add to the database."}, status=400)

    return JsonResponse({"message": "Step added successfully", "name": step_name, "value": new_step.id}, status=201)

def saved_videos(request):

    if request.user.is_student == False:
        return render(request, "danceapp/error.html", {
                "message": "Sorry, only student profiles can see this page."
            })

    return render(request, "danceapp/saved_videos.html")

@login_required(login_url='/login')
def new_video(request):
    
    if request.method == 'POST':
        
        if request.user.is_student == True:
            return render(request, "danceapp/error.html", {
                "message": "Sorry, only teacher or admin profiles can add new videos."
            })
            
        # Take in the data the user submitted and save it as form
        form = NewVideoForm(request.POST)
        
        # Checks if form data is valid (server-side)
        if form.is_valid():
            # Sets author field in new listing
            form.instance.author = request.user
            
            # Saves new listing
            new_video = form.save()
            
            # Gets students from form
            students = form.cleaned_data.get('student_access')

            # Iterates through students
            for student in students:
                
                user_student = student.user

                # Works out name to show in notification text
                if request.user.first_name != '':
                    message_name = request.user.first_name
                else:
                    message_name = request.user.username

                message = f"{message_name} uploaded a new video: {form.cleaned_data.get('title')}"
                
                # Adds a notification to notify them of the new video
                notification = Notification(video=new_video, user=user_student, author=request.user, message=message)
                notification.save()

                # Increments the students total unread notifications by 1
                user_student.unread_notifications += 1
                user_student.save()

            # Redirect to listing page 
            return HttpResponseRedirect(reverse("index",))
        else:
            return render(request, "danceapp/error.html", {
                "message": "An error has occurred. Please try again."
            })
    else:
        if request.user.is_teacher or request.user.is_staff:
            try:
                YOUTUBE_API_KEY = settings.YOUTUBE_API_KEY
            except:
                YOUTUBE_API_KEY = ''
                pass
            
            return render(request, "danceapp/newvideo.html", {
                "form": NewVideoForm(),
                "YOUTUBE_API_KEY": YOUTUBE_API_KEY
            })
        else:
            return render(request, "danceapp/error.html", {
                "message": "You do not have permission to see this page."
            })

# All notifications
def notifications(request):
    return render(request, "danceapp/notifications.html")

@login_required(login_url='/login')
@csrf_exempt
def reset_notifications_counter(request):
    try:
        user = User.objects.get(pk=request.user.pk)
    except User.DoesNotExist:
        return JsonResponse({"error": "User not found."}, status=404)
    
    if request.method != "POST":
        return JsonResponse({"error": "Invalid request. POST request required."}, status=404)
    else: 
        user.unread_notifications = 0
        user.save()

        return JsonResponse({"message": "Notifications reset"}, status=201)

@login_required(login_url='/login')
@csrf_exempt
def read_notification(request, notification_id):
    try: 
        notification = Notification.objects.get(pk=notification_id)
        
    except Notification.DoesNotExist:
        return JsonResponse({"error": "Notification not found"}, status=404)
    
    if request.method != "POST":
        return JsonResponse({"error": "Invalid request. POST request required."}, status=404)
    else:
        notification.read = True
        notification.save()

        return JsonResponse({"message":"Success"}, status=201)

@login_required(login_url='/login')
@csrf_exempt
def read_all_notifications(request):
    # Get user from request
    try:
        user = User.objects.get(pk=request.user.pk)
    except User.DoesNotExist:
            return JsonResponse({"error": "User not found"}, status=404)
    
    if request.method != "POST":
        return JsonResponse({"error": "Invalid request. POST request required."}, status=404)
    else:
        # Find unread notifications for user
        unread_notifications = request.user.notifications.all().filter(read=False)

        # Iterate through unread notifications and mark as read
        for notification in unread_notifications:
            notification.read = True
            notification.save()

        return JsonResponse({"message":"Success"}, status=201)


@login_required(login_url='/login')
def video(request, video_id):
    if request.method != "GET":
        return render(request, "danceapp/error.html", {
                "message": "An error has occurred."
            })
    try: 
        video = Video.objects.get(pk = video_id)
        comments = video.comments.all()
        
    except Video.DoesNotExist:
        return render(request, "danceapp/error.html", {
                "message": "An error has occurred. This video doesn't exist."
            })
    
    return render(request, "danceapp/video.html", {
        "video": video,
        "comment_form": CommentForm(),
        "comments": comments
    })

@login_required(login_url='/login')
@csrf_exempt
def update_favourites(request, video_id):
    
    # Adding to favourites must be via POST
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)
    
    # Find user
    try:
        user = request.user
    except User.DoesNotExist:
        return JsonResponse({"error": "User cannot be found"}, status=400)

    if user.is_student != True:
        return JsonResponse({"error": "Only students can save videos"}, status=400)

    # Saves student instance of user
    user = request.user.student

    # Finds video
    try:
        video = Video.objects.get(pk = video_id)
    except Video.DoesNotExist:
        return JsonResponse({"error": "Video not found"}, status=404)

    # If the video is in user's favourites, remove it
    if (user.favourites.filter(pk=video_id).exists()):
        video.saved_by.remove(user)
        in_favourites = False
    # If the video is not in favourites, add it
    else: 
        video.saved_by.add(user)
        in_favourites = True

    # We pass back the in_favourites parameter to build logic to update the page
    return JsonResponse({"in_favourites": in_favourites}, status=200)

danceapp/templates/danceapp/change_password.html
{% extends "danceapp/layout.html" %}

{% block title %}Change Password {% endblock %}

{% block body %}
    <div class="row justify-content-center">

        <div class="col col-sm-8 col-md-6 col-lg-5 d-flex flex-column align-self-center justify-content-center border rounded py-4 my-0 my-sm-4">

            <h2 class="text-center title pt-1 pb-3">Change Password</h2>

            {% for message in messages %}
                <div class="mx-4 alert {{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}

            <form action="{% url 'change_password' %}" method="POST" class="px-4">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label name="{{ field.name }}" for="{{ form.field.id_for_label }}">{{ field.label }}</label>    
                        <small>{{ field.help_text }}</small>
                        {{ field }}
                        <div class="pt-2 text-danger">
                            <small>{{ field.errors }}</small>
                        </div>
                    </div>
                {% endfor %}
                <div class="text-center">
                    <input class="btn btn-primary btn-block" type="submit" value="Save">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

danceapp/templates/danceapp/error.html
{% extends "danceapp/layout.html" %}

{% block body %}

<div class="d-flex flex-column justify-items-center align-items-center pt-5">
    <div class="border bg-light py-5 px-5">
        <h1 class="text-center">oops..</h1>
        {{ message }}
    </div>
</div>

{% endblock %}

danceapp/templates/danceapp/index.html
{% extends "danceapp/layout.html" %}
{% load static %}

{% block title %}Home {% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-light d-flex justify-content-center">
        <div class="d-flex">
            
            <button class="btn" type="button" id="filter-toggle">
                <i class="fas fa-filter"></i>
            </button>

            <div id="titleContainer" class="form-inline">
                <div class="input-group">
                    <input type="search" class="form-control" placeholder="Search title" aria-label="Search title" id="title_input">
                    <div class="input-group-append">
                        <button class="btn btn-pink" type="button" id="search_title" name="Search title">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="row justify-content-center">
        <!-- FILTERS SIDE BAR -->
        <div id="filter-container" class="filters-sidebar d-none mx-auto">
            <!-- Style -->
            <div class="form-group filter-section">
                <div class="filter-label">Style</div>
                <select class="form-control" id="search_style">
                    <option value="" selected>All</option>
                    {% for style in styles %}
                        <option value="{{ style.pk }}">{{ style.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- Steps -->
            <div class="form-group filter-section d-none" id="steps">
                <div class="filter-label">Step</div>
                <select class="form-control" id="search_step">
                    <option value="" selected>All</option>
                    {% for step in steps %}
                        <option value="{{ step.pk }}">{{ step.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- Teacher -->
            <div class="form-group filter-section">
                <div class="filter-label">Teacher</div>
                <select class="form-control" id="search_teacher">
                    <option value="" selected>All</option>
                    {% for teacher in teachers %}
                        <option value="{{ teacher.pk }}">{{ teacher.user.first_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- Level -->
            <div class="form-group filter-section">
                <div class="filter-label">Level</div>
                <select class="form-control" id="search_level">
                    <option value="" selected>All</option>
                    {% for value, level in levels %}
                        <option value="{{ value }}">{{level}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="d-flex flex-wrap justify-content-center align-items-center col-12 col-lg-10 containerVideos" id="videoContainer">
            
        </div>    
        
    </div>
{% endblock %}


{% block script %}
<script type="module" src="{% static 'danceapp/js/videos.js' %}"></script>
{% endblock %}

danceapp/templates/danceapp/login.html
{% extends "danceapp/layout.html" %}
{% load static %}

{% block title %}Login {% endblock %}

{% block body %}

<div class="d-flex mt-2 mt-sm-5 flex-column align-content-center justify-content-center">
        
    <div class="align-self-center text-center py-5 px-3 px-sm-4 px-md-5">
        <img src="{% static 'danceapp/images/couple.png' %}" alt="Couple dancing together" class="mb-3 login-icon">
        <h2 class="text-center title pb-3">Login</h2>

        {% for message in messages %}
            <div class="alert {{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}

        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" autofocus type="text" name="username" placeholder="Username" required>
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password" required>
            </div>
            <input class="btn btn-lg btn-primary btn-block mt-2 mb-2" type="submit" value="Login">
        </form>

        <small>Don't have an account? <a href="{% url 'register_student' %}">Register as a student here.</a></small>

    </div>

</div>

{% endblock %}

danceapp/templates/danceapp/newvideo.html
{% extends "danceapp/layout.html" %}
{% load static %}

{% block title %}New Video {% endblock %}

{% block body %}

    <h2 class="text-center title pt-3">New Video</h2>

    <div class="row justify-content-center">
        <div class="form-group col-sm-10 col-md-8 col-lg-5">
            <label for="videoInputLink">YouTube URL:</label>
            <input class="form-control" type="text" id="videoInputLink">
            <small id="passwordHelpBlock" class="form-text text-muted">
                Make sure to copy and paste the URL directly from YouTube.
            </small>
            <div class="text-center">
                <button class="btn btn-primary mt-3 btn-block" id="add-new-video">Load video</button>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="form-group col-sm-10 col-md-8 col-lg-5 d-none" id="newVideoForm">
            <form action="{% url 'new_video' %}" method="POST" id="video_form">
                {% csrf_token %}

                {% for field in form %}
                    {% if field.name == 'calena_steps' %}
                    <div id="steps-container" class="d-none mb-2">

                        <div class="form-group mb-0" id="steps">
                            {{ field.label_tag }}
                            <ul class="d-flex flex-wrap mb-0" id="all-steps">
                                {% for pk, choice in field.field.widget.choices %}
                                <li class="pr-3 pb-2">
                                    <label for="id_{{field.name}}_{{ forloop.counter0 }}">
                                    <input id="id_{{field.name}}_{{ forloop.counter0 }}" name="{{field.name}}" type="checkbox" value="{{pk}}" />
                                    {{ choice }}
                                    </label>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div id="steps-error" class="mb-3 text-danger"></div>
                        <a class="btn btn-pink mb-2" id="add-new-step-button">Add new step</a>                        

                    </div>
                    
                    {% else %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                    {% endif %}
                {% endfor %}

                <button type="submit" class="btn btn-primary">Add video</button>
            </form>
        </div>
    </div>

    <div class="row justify-content-center mx-2 mx-sm-0 d-none" id="error_container">
        <div class="alert alert-danger mt-4 pt-4 pb-3 col-sm-10 col-md-8 col-lg-5">
            <h5 class="alert-heading">Oops!</h5>
            <p id="error_message"></p>
        </div>
    </div>
    

{% endblock %}

{% block script %}
<script>
    let YOUTUBE_API_KEY ='{{ YOUTUBE_API_KEY }}';
</script>
<script src="{% static 'danceapp/js/newvideo.js' %}" async></script>
<script src="{% static 'danceapp/js/calena_step.js' %}" async></script>
{% endblock %}

danceapp/templates/danceapp/notifications.html
{% extends "danceapp/layout.html" %}
{% load static %}
{% load humanize %}

{% block title %}Notifications {% endblock %}

{% block body %}
    <div class="row justify-content-center pt-2">
        
        <div class="col-12 col-sm-8 col-md-6 col-lg-4 notification-shadow pt-3 pb-0 px-0">
            <div class="d-flex border-bottom align-items-center justify-content-between px-4 pb-3">
                <h2 class="text-center mb-0">Notifications</h2>
                {% if notifications %}
                    <a class="mark-read" class="my-0" href="javascript:void(0)">Mark all as read</a>
                {% endif %}
            </div>
            
            {% include "danceapp/notifications_block.html" %}

        </div>
    </div>
{% endblock %}

danceapp/templates/danceapp/video.html
{% extends "danceapp/layout.html" %}
{% load static %}
{% load humanize %}

{% block title %} {{ video.title }} {% endblock %}

{% block body %}
        
    <div class="mx-auto my-4" style="max-width: 900px;">
        <div class="video-container">
            <iframe src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allowfullscreen; modestbranding;></iframe>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12 col-md-11 px-4 px-md-1 mx-sm-auto" style="max-width: 900px;">
            
            <div class="d-flex justify-content-between video-page-title text-pink">
                <h1>{{ video.title }}</h1>
                {% if user.is_student %}
                    <h1 class="pl-2 pr-md-3" data-video_id="{{video.pk}}" id="save-video"><i id="heart-icon" class="{% if user.student in video.saved_by.all %}fas fa-heart{% else %}far fa-heart{% endif %}"></i></h1>
                {% endif %} 
            </div>

            <p style="white-space: pre-line; max-width: 600px;">{{video.description}}</p>
            
            <div id="video-details-mobile" class="font-weight-bold text-pink border-bottom pt-2 pb-1">Video details</div>
            <div class="d-flex py-2 videopage-icons border-bottom">
                <div class="pb-2"><i class="far fa-calendar-alt card-icon"></i> {{ video.class_date|date:"d/m/y"}} </div>
                <div class="pb-2"><i class="fas fa-tags card-icon"></i> {{ video.style }}</div>
                <div class="pb-2"><i class="fab fa-deezer card-icon"></i> {{ video.get_level_display }}</div>
                <div class="d-flex pb-2">
                    {% for teacher in video.teacher.all %}
                        <div class="pr-2"><i class="fas fa-user pr-1 card-icon"></i>{{ teacher }}</div>
                    {% endfor %}
                </div>
            </div>
        
        </div>
    </div>
    
    <div class="row">
        <div class="col-12 col-md-11 px-4 px-md-1 mx-sm-auto" style="max-width: 900px;">
            
            <div class="pt-3" id="comment_counter_text">
                {% if comments.count > 0 %}
                    {{ comments.count }}{% if comments.count > 1 %} comments{% else %} comment{%endif%}
                {% else %}
                    Be the first to leave a comment!
                {% endif %}
            </div>

            <div class="form-group p-4 border-bottom">
                <form action="{% url 'add_comment' video.id %}" method="POST">
                    {% csrf_token %}
                    <div class="d-flex">
                        <img class="circular-picture comment-picture" src="{% if user.profile_picture %}{{ user.profile_picture }}{% else %}{% static 'danceapp/images/no-profile-pic.png' %}{% endif %}" alt="profilepic">
                        {{ comment_form }}

                    </div>
                    <div id="comment-buttons" class="text-right mt-3 d-none">
                        <a id="cancel-comment" class="btn btn-pink-outline mr-2">Cancel</a>
                        <button id="add-comment" class="btn btn-pink">Add comment</button>
                    </div>
                </form>
            </div>

            <div class="comments" style="font-size: 14px;">
                {% for comment in comments %}
                    <div class="comment-item d-flex" id="comment-{{comment.pk}}">
                        <img class="circular-picture comment-picture" src="{% if comment.author.profile_picture %}{{comment.author.profile_picture}}{% else %}{% static 'danceapp/images/no-profile-pic.png' %}{% endif %}" alt="profilepic">
                        <div class="d-flex flex-column pl-3">
                            <div class="d-flex">
                                <div class="comment-name font-weight-bold">{{ comment.author.first_name }} {{ comment.author.last_name }}</div>
                                <div class="comment-time text-muted pl-2">{{ comment.time|naturaltime }}</div>
                                <!-- delete-comment class is used in JavaScript - do not remove -->
                                {% if user == comment.author %}<div class="pl-2 delete-comment" data-comment_id="{{comment.pk}}"><i class="far fa-trash-alt"></i></div>{% endif %}
                            </div>
                            <div class="comment-text">{{ comment.comment }}</div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    

{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'danceapp/js/comments.js' %}" defer></script>
{% if user.is_student %}
    <script type="text/javascript" src="{% static 'danceapp/js/likevideo.js' %}" defer></script>
{% endif %}

{% endblock %}